version: '3'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - 81:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: apache.log
    links:
      - fluentd
    depends_on:
      - fluentd
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    #logging:
    #  driver: "fluentd"
    #  options:
    #    fluentd-address: localhost:24224
    #    tag: nginx.log
    links:
      - fluentd
    depends_on:
      - fluentd

  fluentd:
    image: fluent/fluentd:latest
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - type: bind
        source: /logs-fluentd/
        target: /fluentd/etc/logs/
      - type: bind
        source: ./fluentd/fluentd.conf
        target: /fluentd/etc/fluentd.conf
    environment:
      FLUENTD_CONF: "fluentd.conf"